### ISSUE TITLE
p63 내장 타입 확장

### ISSUE THREAD

**Issue by castedice** [nullstack-developer/python_clean_code#4]
>예를 들어 diet를 직접 확장하는 클래스를 만들면 예상하지 못한 결과를 얻을 수 있다. 그 이유는 CPython에서는 (당연하게도) 클래스의 메서드를 서로 호출하지 않기 때문에 메서드 중에 하나를 오버라이드하면 나머지에는 반영되지 않아서 예기치 않은 결과가 발생한다. 예를 들어 __getitem_을 오버라이드하고 for 루프를 사용해 객체를 반복하려고 하면 해당 로직이 적용되지 않은 것을 알게 된다.

해당 내용에 대해서 더 찾아보려 했으나 딱히 도움이 될만한 자료를 찾지 못함
추론해보자면, cpython의 내장 함수의 경우 저번에 `range`를 뜯어봤던 것처럼 내부적으로 구현이 되어 있는 것이 아니라 인터페이스 형태로만 남아있음
내부적으로는 c 구현체들을 바로 연결해서 실행시키는 것으로 추정됨
특정 메서드의 c 구현체를 오버라이딩 하더라도 다른 메서드의 c 구현체가 오버라이딩되지 않으므로 이러한 문제가 발생하는 것이 아닐까 추정
즉, cpython의 내장 타입의 구현체들은 서로를 객체지향적으로 참조하는 것이 아니라 같은 로직이라면 복사 붙여넣기 형태로 구현되어 있을 가능성이 높다고 생각됨

관련하여 논의해봤으면 좋겠음

**Comment by jangsc0000** [comment]
리스트, 문자열, 사전과 내장 타입 확장은 반드시 collection 모듈을 사용해야함
